name: F1

profile: F1

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  F1:
    +schema: raw

models:
  +persist_docs:
    relation: true
    columns: true
  F1:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table
